services:
  - type: web
    name: myapp
    env: docker
    dockerfilePath: Dockerfile

    envVars:
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: us-east-2
