services:
  - type: web
    name: myapp
    env: docker
    buildCommand: docker build \
      --build-arg AWS_ACCESS_KEY_ID \
      --build-arg AWS_SECRET_ACCESS_KEY \
      --build-arg AWS_REGION \
      -t myapp .

    envVars:
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: us-east-2
